name: CI GitHub Actions

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        # Aquí especificamos el archivo de solución para evitar el error MSB1011
        run: dotnet restore test1.sln

      - name: Build (Paso a)
        run: dotnet build test1.sln --no-restore

      - name: Test (Paso b)
        run: dotnet test test1.sln --no-build --verbosity normal